name: Merge Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist

      - name: Run Pint
        run: |
          echo "Running Pint..."
          vendor/bin/pint

      - name: Run PHPStan
        run: |
          echo "Running PHPStan..."
          vendor/bin/phpstan

      - name: Run Psalm
        run: |
          echo "Running Psalm..."
          vendor/bin/psalm

      # Step 8: Run Tests
      - name: Run Tests
        run: |
          echo "Running Tests..."
          php artisan test

      - name: Success message
        if: success()
        run: echo "Todas as validações ocorreram com sucesso, prosseguindo com o merge."
